### ISSUE TITLE
How can I mock no internet response by Mocker?

### ISSUE THREAD

**Issue by nhatduy129** [WeTransfer/Mocker#100]
I want to test the case which there is no internet. Is it possible for me to do that by using Mocker?

**Comment by nonegu** [comment]
Hello,

There is a high chance that you have already find a solution, but in any case, I would like to share my approach.

I had the same case and used `requestError:` on the public initializer of Mock class. I created a custom `NSError` with code `NSURLErrorNotConnectedToInternet` and passed it. 
 
You may use a similar approach for any kind of request failures. Mocker will return the error instead of the data as it is explained in the [Mock class](https://github.com/WeTransfer/Mocker/blob/master/Sources/Mock.swift).
 `/// If set, the error that URLProtocol will report as a result rather than returning data from the mock
    public let requestError: Error?`

**Comment by nhatduy129** [comment]
> Hello,
> 
> There is a high chance that you have already find a solution, but in any case, I would like to share my approach.
> 
> I had the same case and used `requestError:` on the public initializer of Mock class. I created a custom `NSError` with code `NSURLErrorNotConnectedToInternet` and passed it.
> 
> You may use a similar approach for any kind of request failures. Mocker will return the error instead of the data as it is explained in the [Mock class](https://github.com/WeTransfer/Mocker/blob/master/Sources/Mock.swift).
> `/// If set, the error that URLProtocol will report as a result rather than returning data from the mock public let requestError: Error?`

Thank to your answer, you help me know that Mock constructor has `requestError`. Instead customise NSError like yours. I pass `URLError(.notConnectedToInternet)` to requestError. It works for me, thank you so much.

**Comment by BasThomas** [comment]
Does that resolve your issue, @nhatduy129? If so, could we close this issue? :)
